import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";


export const metadata: Metadata = {
  title: "Персональная страница Игоря Корякова",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar />
        <main className="fadein">{children}</main>
        <Footer />
      </body>
    </html>
  );
}