import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import "../globals.css";
import Navbar from "../../../components/Navbar";
import Footer from "../../../components/Footer";

export const metadata: Metadata = {
  title: "Персональная страница Игоря Корякова",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = params;
  let messages = {};
  try {
    messages = (await import(`../../lang/${locale}.json`)).default;
  } catch {
    // Optionally handle missing locale/messages
  }

  console.log("Loaded messages for locale:", locale, messages); // <--- ADD THIS LINE

  return (
    <>
      
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          <main className="fadein">{children}</main>
          <Footer />
        </NextIntlClientProvider>
      
    </>
  );
}